services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python-server/src:/app/src
    # Ensure uvicorn binds to 0.0.0.0 so it's reachable from the host
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    # Mount source for live reload with nodemon, keep node_modules from image
    volumes:
      - ./express-server:/usr/src/app
      - express_node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
    depends_on:
      - python-server

volumes:
  express_node_modules: