version: "3.8"

services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python-server/src:/app/src
    command: >
      uvicorn src.main:app --host 0.0.0.0 --port 8000

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"s
    volumes:
      - ./node-server/src:/app/src
    environment:
      - NODE_ENV=development
    command: npm start
